---
- hosts: 127.0.0.1
  connection: local
    
  tasks:
    - shell: ./find_markdown.py
      register: markdowns_raw

    - set_fact: markdowns="{{ markdowns_raw.stdout | from_json }}"

    - debug:
        msg: "{{ markdowns }}"
    
    - template:
        src: "README.md.j2"
        dest: "README.md"
      notify: commit and push

  handlers:
    - name: commit and push
      shell: |
        git config user.name "CircleCI"
        git config user.email "noreply@circleci.com"
        git add README.md
        git commit -m "Added newly generated README"
        git push origin master
