---
- hosts: 127.0.0.1
  connection: local
    
  tasks:
    - shell: ./.template/find_markdown.py
      register: markdowns_raw

    - shell: "git log -1 --pretty=format:'%an' | grep CircleCI"
      register: circleci_commit
      ignore_errors: yes

    - set_fact: markdowns="{{ markdowns_raw.stdout | from_json }}"

    - debug:
        msg: "{{ markdowns }}"
    
    - template:
        src: "./.template/README.md.j2"
        dest: "README.md"
      notify: generated
      when: circleci_commit.rc == 1

  handlers:
    - name: commit and push
      shell: |
        git config user.name > /dev/null || git config user.name "CircleCI"
        git config user.email > /dev/null || git config user.email "noreply@circleci.com"
        git add README.md
        git commit --message "Added newly generated README" --author "CircleCI <noreply@circleci.com>"
        git push origin master
      listen: "generated"
