version: 2

jobs:
    deploy:
        docker:
            - image: circleci/python:3.7.7
        working_directory: ~/til
        steps:
            - checkout
            - run: 
                name: Download ansible
                command: apt-get instally -y ansible
            - run:
                name: Generate README
                command: ansible-playbook playbook.yml
workflows:
    version: 2
    commit-workflow:
        jobs:
            - deploy:
                filters:
                    branches:
                        only: master