version: 2

jobs:
    deploy:
        docker:
            - image: circleci/python:3.7.7
        working_directory: ~/til
        steps:
            - checkout
            - run:
                name: list directory contents
                command: ls
            - run: 
                name: Update apt-get
                command: sudo apt-get update -y 
            - run: 
                name: Download ansible
                command: sudo apt-get install -y ansible
            - run: 
                name: Download mkdocs
                command: sudo apt-get install -y mkdocs python3-pip
            - run: 
                name: Download Theme
                command: pip install mkdocs-material
            - run: 
                name: Build docs
                command: mkdocs build
            - run:
                name: Generate README
                command: ansible-playbook playbook.yml
workflows:
    version: 2
    commit-workflow:
        jobs:
            - deploy:
                filters:
                    branches:
                        only: master