version: 2

jobs:
    deploy:
        docker:
            - image: circleci/python:3.9.4
        working_directory: ~/til
        steps:
            - checkout
            - run:
                name: list directory contents
                command: ls
            - run: 
                name: Update apt-get
                command: sudo apt-get update -y --allow-releaseinfo-change
            - run: 
                name: Download ansible
                command: sudo apt-get install -y ansible
            - run: 
                name: Download MkDocs
                command: python -m pip install mkdocs-material
            - run: 
                name: Build docs
                command: mkdocs gh-deploy
            - run:
                name: Generate README
                command: ansible-playbook playbook.yml
    skip:
        machine: true
        steps:
            - run:
                name: Skip
                command: echo "Skipping branch build"


workflows:
    version: 2
    commit-workflow:
        jobs:
            - deploy:
                filters:
                    branches:
                        only: master
    gh-pages-workflow:
        jobs:
            - skip:
                filters:
                    branches:
                        only: gh-pages