name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - master
    paths:
      - README.md
      - mkdocs/**

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        # Or use mhausenblas/mkdocs-deploy-gh-pages@nomaterial to build without the mkdocs-material theme
        env:
          CONFIG_FILE: mkdocs/mkdocs.yml
          REQUIREMENTS: mkdocs/requirements.txt