name: Update README.md
concurrency: ci-${{ github.ref }}
on:
    push:
      branches:
        - master
      paths:
        - 'notes.ttl'
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        env:
            CI_COMMIT_MESSAGE: Generate new README
            CI_COMMIT_AUTHOR: Github Actions
        steps:
            - uses: actions/checkout@v3
            - name: Generate notes catalog
              run: python ./.template/readme/generate_data.py > data.json
            - name: Generate README.md
              uses: cuchi/jinja2-action@v1.2.0
              with:
                template: ./.template/readme/README.md.j2
                output_file: README.md
                data_file: data.json
                data_format: json
            - name: Verify Changed files
              uses: tj-actions/verify-changed-files@v16
              id: verify-changed-files
              with:
                files: |
                    README.md
            - name: Push README.md updates
              if: steps.verify-changed-files.outputs.files_changed == 'true'
              run: |
                git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
                git config --global user.email "noreply@github.com"
                git add README.md
                git commit --message "${{ env.CI_COMMIT_MESSAGE }}"
                git push
